baseUrl=https://restful-booker.herokuapp.com
allurePath=C:\\Users\\Sama7h\\.m2\\repository\\allure\\allure-2.42.0\\bin\\allure.bat
executionType=local
allure.results.directory=test-output/allure-results
OpenAllureReportAfterExecution=true