baseUrl=https://restful-booker.herokuapp.com
allurePath=C:\\Users\\Win11\\.m2\\repository\\allure\\allure-2.43.0\\bin\\allure.bat
executionType=local
allure.results.directory=test-output/allure-results
OpenAllureReportAfterExecution=true