# Auth Data
valid.username=admin
valid.password=password123
invalid.password=wrongPassword

# Error Messages
error.bad.credentials=Bad credentials
error.internal.server=Internal Server Error
error.not.found=Not Found

# Booking Data
valid.firstname=Enas
valid.lastname=Ehab
valid.totalprice=150
valid.depositpaid=true
valid.checkin=2027-01-01
valid.checkout=2027-01-10
valid.additionalneeds=Breakfast

# Update Booking
updated.firstname=samah
updated.lastname=sameh
updated.totalprice=250
updated.depositpaid=false
updated.checkin=2026-08-01
updated.checkout=2026-08-10
updated.additionalneeds=Lunch